services:
  web:
    image: birbalsarva/budget-app_web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/budjet_demo_db"
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budjet_demo_db
